       IDENTIFICATION DIVISION.
       PROGRAM-ID. HappyBirthday.

       PROCEDURE DIVISION.

           DISPLAY "***************************************************"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "*                                                 *"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "*                                                 *"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "*                 Happy Birthday!                 *"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "*                                                 *"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "*                                                 *"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "***************************************************"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "CCCLLfffffffLLLLLfffffffftttttttfLLLCCCCLLLCLLLLLCC"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "tt11111111ttffffffLCCCCCLLLfft111tfLLLLLLLfftfLLLLL"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "1111111tfffffttfCG0GGCCLLLCCLfLLfffLfffLLfft11fLLLf"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "tttftttfffftttCGGGLffffffffLfLLLLLLLffffttffftfffff"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "ffffffftttttLGCCCfttttt1tffffffLfffLftt111tffffffff"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "tttttttttttfCffft11111tfLCCGGCLfLffLLLfttttttttttff"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "LLLffffttttCLfLftttfffLCGGGG00GLLCLLCLLffffffffffff"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "LLLLLLfftttCLGCCCCCGGGGGGGGGG00GLCCCCLLLLLLLLLLLLLL"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "LLLLLLLLLLLCLGCCCCCCGGGGGGGGGG0GGCLCCCCLLLLLLfffLLL"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "GCCLLLLCLLfLfLCCGGGGCCCCGGGGGG0000CCCGCLLLLLLLLLLLL"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "GGCCCLLLLfffLLGCCCLLLLLLftt1tffCG00CCLCLLCCCLCCGGGC"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "CLLLLLLLLLLLLCCt11111fLLt11tfLLCG00GGCCLLLCLfLLLLLL"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "LLLLfffLffLLfCCfttttffGGCCCCCGGGG00GG0CLLLftttfffft"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "LfLLLCCCCCLLCCGGGCCCLLG00GCLCCCGGGGGCLLLLLLLLLLCLLL"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "ffLLCCCCCCCCLLCCCCCLfLCGGGCLLLLLCCGGG0GLLLfffffffLL"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "LLLLLLfLLLLLLLLCLLffLLtttffLLffLCLCGGG@80000GG0GLLL"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "LLLLLLfLLLLLCCCLLffffffttffLCLffLLCGGL88888@8@88@88"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "LLLLLLLLLLffLLLfffftfLLLffLCCCLffLLGCL88880808808@@"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "LLLLLLLLLLLLLLLC08GftfLCCCCCLLffffLCLC888888000G088"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "fffLLLLLLCCLCG888880CttttttttttffLLLLG088880800G088"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "ffffffLLLLCG888800800LfftttttttffLffCLfLCG0G000G000"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "LLLffLLLC08@8000008000CLttffffffffLCCLLLLC00000GG00"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "fffLLLC08@880000008880GGCffffffffCGCCGCCGG00000GG00"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "LLLLC08@88880000000GCLfLGGCCCCLfCGGGGGCGGG000000GGG"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "CCC0888888880000000CCCCLLCCCCCGGCG000GGGGGG00000GGG"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "***************************************************"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "*                                                 *"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "*                                                 *"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "*                 Happy Birthday!                 *"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "*                                                 *"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "*                                                 *"
           CALL "CBL_OC_NANOSLEEP" USING BY CONTENT 80000000
           DISPLAY "***************************************************"

           GOBACK
           .

